// AUTO-GENERATED — run `pnpm gen:api-diff` to regenerate. Do not edit manually.
// Generated: 2026-07-07T13:37:19.413Z

export interface ApiDiffEntry {
  route: string;
  category: 'real' | 'temp-api' | 'proto-no-hook';
  ops: string[];
  missingOps: string[];
  protoFile: string | null;
  hookFile: string | null;
  hasMockData: boolean;
  notes: string | null;
  pages: string[];
}

export const API_DIFF_MANIFEST: ApiDiffEntry[] = [
  {
    route: 'v1/compute_instances',
    category: 'temp-api',
    ops: ['create', 'delete', 'get', 'list', 'patch'],
    missingOps: [],
    protoFile: null,
    hookFile: 'compute-instance.ts',
    hasMockData: true,
    notes: null,
    pages: ['/admin/dashboard', '/ips', '/networks', '/provider/dashboard', '/storage/snapshots', '/storage/volumes', '/vms', '/vms/:id', '/vms/create/:catalogItemId?'],
  },
  {
    route: 'v1/compute_instance_templates',
    category: 'temp-api',
    ops: ['create', 'delete', 'get', 'list', 'patch'],
    missingOps: [],
    protoFile: null,
    hookFile: 'compute-instance-templates.ts',
    hasMockData: true,
    notes: null,
    pages: ['/provider/catalog-studio', '/provider/catalog-studio/new', '/provider/catalog/:id/edit', '/provider/catalog/new', '/provider/templates', '/provider/templates/vm/:id/edit', '/provider/templates/vm/new'],
  },
  {
    route: 'v1/compute_instance_catalog_items',
    category: 'temp-api',
    ops: ['create', 'delete', 'get', 'list', 'patch'],
    missingOps: [],
    protoFile: null,
    hookFile: 'compute-instance-catalog-item.ts',
    hasMockData: true,
    notes: null,
    pages: ['/admin/catalog', '/catalog', '/provider/catalog', '/provider/catalog-studio', '/provider/catalog-studio/new', '/provider/catalog/:id/edit', '/provider/catalog/new'],
  },
  {
    route: 'v1/clusters',
    category: 'temp-api',
    ops: ['create', 'delete', 'get', 'list'],
    missingOps: [],
    protoFile: null,
    hookFile: 'cluster.ts',
    hasMockData: true,
    notes: null,
    pages: ['/clusters', '/clusters/:clusterId', '/provider/ai-setup', '/provider/catalog-studio'],
  },
  {
    route: 'v1/cluster_templates',
    category: 'temp-api',
    ops: ['create', 'delete', 'get', 'list', 'patch'],
    missingOps: [],
    protoFile: null,
    hookFile: 'cluster-templates.ts',
    hasMockData: true,
    notes: null,
    pages: ['/provider/catalog-studio', '/provider/catalog-studio/new', '/provider/catalog/:id/edit', '/provider/catalog/new', '/provider/templates'],
  },
  {
    route: 'v1/cluster_catalog_items',
    category: 'temp-api',
    ops: ['create', 'delete', 'get', 'list', 'patch'],
    missingOps: [],
    protoFile: null,
    hookFile: 'cluster-catalog-item.ts',
    hasMockData: true,
    notes: null,
    pages: ['/admin/catalog', '/catalog', '/provider/catalog', '/provider/catalog-studio', '/provider/catalog-studio/new', '/provider/catalog/:id/edit', '/provider/catalog/new'],
  },
  {
    route: 'v1/baremetal_instances',
    category: 'temp-api',
    ops: ['create', 'delete', 'get', 'list', 'patch'],
    missingOps: [],
    protoFile: null,
    hookFile: 'baremetal-instance.ts',
    hasMockData: true,
    notes: null,
    pages: ['/admin/catalog', '/bare-metal', '/catalog', '/provider/catalog'],
  },
  {
    route: 'v1/baremetal_instance_templates',
    category: 'temp-api',
    ops: ['create', 'delete', 'get', 'list'],
    missingOps: [],
    protoFile: null,
    hookFile: 'baremetal-instance-templates.ts',
    hasMockData: true,
    notes: null,
    pages: ['/provider/catalog-studio', '/provider/catalog-studio/new', '/provider/catalog/:id/edit', '/provider/catalog/new', '/provider/templates'],
  },
  {
    route: 'v1/baremetal_instance_catalog_items',
    category: 'temp-api',
    ops: ['create', 'delete', 'get', 'list', 'patch'],
    missingOps: [],
    protoFile: null,
    hookFile: 'baremetal-instance-catalog-item.ts',
    hasMockData: true,
    notes: null,
    pages: ['/admin/catalog', '/catalog', '/provider/catalog', '/provider/catalog-studio', '/provider/catalog-studio/new', '/provider/catalog/:id/edit', '/provider/catalog/new'],
  },
  {
    route: 'v1/host_types',
    category: 'temp-api',
    ops: ['create', 'delete', 'get', 'list', 'patch'],
    missingOps: [],
    protoFile: null,
    hookFile: 'host-types.ts',
    hasMockData: true,
    notes: null,
    pages: ['/provider/catalog-studio', '/provider/host-types', '/provider/host-types/new'],
  },
  {
    route: 'v1/instance_types',
    category: 'temp-api',
    ops: ['create', 'delete', 'get', 'list', 'patch'],
    missingOps: [],
    protoFile: null,
    hookFile: 'instance-types.ts',
    hasMockData: true,
    notes: null,
    pages: ['/provider/catalog-studio', '/provider/instance-types', '/provider/instance-types/new', '/provider/templates/vm/:id/edit', '/provider/templates/vm/new'],
  },
  {
    route: 'v1/virtual_networks',
    category: 'temp-api',
    ops: ['create', 'delete', 'get', 'list', 'patch'],
    missingOps: [],
    protoFile: null,
    hookFile: 'networking.ts',
    hasMockData: true,
    notes: null,
    pages: ['/networks/:id', '/networks/new', '/networks/security-groups/:id/rules', '/networks/security-groups/new', '/networks/subnets/new', '/provider/network-classes', '/provider/network-classes/new'],
  },
  {
    route: 'v1/subnets',
    category: 'temp-api',
    ops: ['create', 'delete', 'get', 'list', 'patch'],
    missingOps: [],
    protoFile: null,
    hookFile: 'networking.ts',
    hasMockData: true,
    notes: null,
    pages: ['/networks/:id', '/networks/new', '/networks/security-groups/:id/rules', '/networks/security-groups/new', '/networks/subnets/new', '/provider/network-classes', '/provider/network-classes/new'],
  },
  {
    route: 'v1/security_groups',
    category: 'temp-api',
    ops: ['create', 'delete', 'get', 'list', 'patch'],
    missingOps: [],
    protoFile: null,
    hookFile: 'networking.ts',
    hasMockData: true,
    notes: null,
    pages: ['/networks/:id', '/networks/new', '/networks/security-groups/:id/rules', '/networks/security-groups/new', '/networks/subnets/new', '/provider/network-classes', '/provider/network-classes/new'],
  },
  {
    route: 'v1/network_classes',
    category: 'temp-api',
    ops: ['create', 'delete', 'get', 'list', 'patch'],
    missingOps: [],
    protoFile: null,
    hookFile: 'networking.ts',
    hasMockData: true,
    notes: null,
    pages: ['/networks/:id', '/networks/new', '/networks/security-groups/:id/rules', '/networks/security-groups/new', '/networks/subnets/new', '/provider/network-classes', '/provider/network-classes/new'],
  },
  {
    route: 'v1/public_ips',
    category: 'temp-api',
    ops: ['create', 'delete', 'get', 'list', 'patch'],
    missingOps: [],
    protoFile: null,
    hookFile: 'ip-management.ts',
    hasMockData: true,
    notes: null,
    pages: ['/ips', '/provider/ip-pools', '/provider/ip-pools/:poolType/:id', '/provider/ip-pools/new', '/vms/create/:catalogItemId?'],
  },
  {
    route: 'v1/public_ip_pools',
    category: 'temp-api',
    ops: ['create', 'delete', 'get', 'list', 'patch'],
    missingOps: [],
    protoFile: null,
    hookFile: 'ip-management.ts',
    hasMockData: true,
    notes: null,
    pages: ['/ips', '/provider/ip-pools', '/provider/ip-pools/:poolType/:id', '/provider/ip-pools/new', '/vms/create/:catalogItemId?'],
  },
  {
    route: 'v1/public_ip_attachments',
    category: 'temp-api',
    ops: ['create', 'delete', 'get', 'list', 'patch'],
    missingOps: [],
    protoFile: null,
    hookFile: 'ip-management.ts',
    hasMockData: true,
    notes: null,
    pages: ['/ips', '/provider/ip-pools', '/provider/ip-pools/:poolType/:id', '/provider/ip-pools/new', '/vms/create/:catalogItemId?'],
  },
  {
    route: 'v1/external_ips',
    category: 'temp-api',
    ops: ['create', 'delete', 'get', 'list', 'patch'],
    missingOps: [],
    protoFile: null,
    hookFile: 'ip-management.ts',
    hasMockData: true,
    notes: null,
    pages: ['/ips', '/provider/ip-pools', '/provider/ip-pools/:poolType/:id', '/provider/ip-pools/new', '/vms/create/:catalogItemId?'],
  },
  {
    route: 'v1/external_ip_pools',
    category: 'temp-api',
    ops: ['create', 'delete', 'get', 'list', 'patch'],
    missingOps: [],
    protoFile: null,
    hookFile: 'ip-management.ts',
    hasMockData: true,
    notes: null,
    pages: ['/ips', '/provider/ip-pools', '/provider/ip-pools/:poolType/:id', '/provider/ip-pools/new', '/vms/create/:catalogItemId?'],
  },
  {
    route: 'v1/external_ip_attachments',
    category: 'temp-api',
    ops: ['create', 'delete', 'get', 'list', 'patch'],
    missingOps: [],
    protoFile: null,
    hookFile: 'ip-management.ts',
    hasMockData: true,
    notes: null,
    pages: ['/ips', '/provider/ip-pools', '/provider/ip-pools/:poolType/:id', '/provider/ip-pools/new', '/vms/create/:catalogItemId?'],
  },
  {
    route: 'v1/tenants',
    category: 'temp-api',
    ops: ['create', 'delete', 'get', 'list', 'patch'],
    missingOps: [],
    protoFile: null,
    hookFile: 'tenant.ts',
    hasMockData: true,
    notes: null,
    pages: ['/provider/catalog-studio/new', '/provider/catalog/:id/edit', '/provider/catalog/new', '/provider/ip-pools', '/provider/ip-pools/new', '/provider/organizations', '/provider/organizations/:id/edit', '/provider/organizations/new'],
  },
  {
    route: 'v1/organizations',
    category: 'temp-api',
    ops: ['list'],
    missingOps: [],
    protoFile: null,
    hookFile: 'organization.ts',
    hasMockData: true,
    notes: null,
    pages: ['/provider/dashboard', '/provider/ip-pools/:poolType/:id'],
  },
  {
    route: 'v1/projects',
    category: 'temp-api',
    ops: ['create', 'delete', 'get', 'list'],
    missingOps: [],
    protoFile: null,
    hookFile: 'project.ts',
    hasMockData: true,
    notes: null,
    pages: ['/projects', '/projects/:id', '/projects/new'],
  },
  {
    route: 'v1/project_memberships',
    category: 'temp-api',
    ops: ['create', 'delete', 'get', 'list'],
    missingOps: [],
    protoFile: null,
    hookFile: 'project-membership.ts',
    hasMockData: true,
    notes: null,
    pages: ['/projects/:id'],
  },
  {
    route: 'v1/users',
    category: 'temp-api',
    ops: ['create', 'list'],
    missingOps: [],
    protoFile: null,
    hookFile: 'user.ts',
    hasMockData: true,
    notes: null,
    pages: ['/admin/dashboard', '/admin/users', '/admin/users/new', '/projects/:id'],
  },
  {
    route: 'v1/roles',
    category: 'temp-api',
    ops: ['create', 'delete', 'get', 'list', 'patch'],
    missingOps: [],
    protoFile: null,
    hookFile: 'role-binding.ts',
    hasMockData: true,
    notes: null,
    pages: ['/admin/role-bindings', '/admin/role-bindings/:id', '/admin/role-bindings/assign'],
  },
  {
    route: 'v1/role_bindings',
    category: 'temp-api',
    ops: ['create', 'delete', 'get', 'list', 'patch'],
    missingOps: [],
    protoFile: null,
    hookFile: 'role-binding.ts',
    hasMockData: true,
    notes: null,
    pages: ['/admin/role-bindings', '/admin/role-bindings/:id', '/admin/role-bindings/assign'],
  },
  {
    route: 'v1/identity_providers',
    category: 'temp-api',
    ops: ['create', 'delete', 'get', 'list', 'patch'],
    missingOps: [],
    protoFile: null,
    hookFile: 'identity-provider.ts',
    hasMockData: true,
    notes: null,
    pages: ['/admin/identity-providers', '/admin/identity-providers/:id/edit', '/admin/identity-providers/new', '/provider/organizations'],
  },
  {
    route: 'v1/console_sessions',
    category: 'temp-api',
    ops: ['create', 'list'],
    missingOps: [],
    protoFile: null,
    hookFile: 'console.ts',
    hasMockData: false,
    notes: null,
    pages: [],
  },
  {
    route: 'v1/capabilities',
    category: 'temp-api',
    ops: [],
    missingOps: [],
    protoFile: null,
    hookFile: null,
    hasMockData: false,
    notes: null,
    pages: [],
  },
  {
    route: 'v1/events',
    category: 'temp-api',
    ops: [],
    missingOps: [],
    protoFile: null,
    hookFile: null,
    hasMockData: false,
    notes: null,
    pages: [],
  },
  {
    route: 'v1/storage_tiers',
    category: 'temp-api',
    ops: ['create', 'delete', 'get', 'list', 'patch'],
    missingOps: [],
    protoFile: null,
    hookFile: 'storage-tier.ts',
    hasMockData: true,
    notes: '@temp-api — not yet in fulfillment-service',
    pages: ['/provider/storage-tiers', '/provider/storage-tiers/:id/edit', '/provider/storage-tiers/new', '/storage/tiers'],
  },
  {
    route: 'v1/block_volumes',
    category: 'temp-api',
    ops: ['create', 'delete', 'get', 'list', 'patch'],
    missingOps: [],
    protoFile: null,
    hookFile: 'block-volumes.ts',
    hasMockData: true,
    notes: '@temp-api — not yet in fulfillment-service',
    pages: ['/storage/volumes', '/storage/volumes/new'],
  },
  {
    route: 'v1/volume_snapshots',
    category: 'temp-api',
    ops: ['create', 'delete', 'get', 'list'],
    missingOps: [],
    protoFile: null,
    hookFile: 'volume-snapshot.ts',
    hasMockData: true,
    notes: '@temp-api — not yet in fulfillment-service',
    pages: ['/storage/snapshots'],
  },
  {
    route: 'v1/object_storage_buckets',
    category: 'temp-api',
    ops: ['create', 'delete', 'get', 'list', 'patch'],
    missingOps: [],
    protoFile: null,
    hookFile: 'object-storage.ts',
    hasMockData: true,
    notes: '@temp-api — not yet in fulfillment-service',
    pages: ['/bucket-storage', '/bucket-storage/:id', '/bucket-storage/:id/edit', '/bucket-storage/new'],
  },
  {
    route: 'v1/bucket_access_keys',
    category: 'temp-api',
    ops: ['create', 'delete', 'get', 'list'],
    missingOps: [],
    protoFile: null,
    hookFile: 'bucket-access-keys.ts',
    hasMockData: true,
    notes: '@temp-api — not yet in fulfillment-service',
    pages: ['/bucket-storage/:id'],
  },
  {
    route: 'v1/load_balancers',
    category: 'temp-api',
    ops: ['create', 'delete', 'get', 'list', 'patch'],
    missingOps: [],
    protoFile: null,
    hookFile: 'load-balancer.ts',
    hasMockData: true,
    notes: '@temp-api — not yet in fulfillment-service',
    pages: ['/load-balancers', '/load-balancers/:id/edit', '/load-balancers/new'],
  },
  {
    route: 'v1/ai_environments',
    category: 'temp-api',
    ops: ['create', 'get', 'list', 'patch'],
    missingOps: [],
    protoFile: null,
    hookFile: 'ai-environment.ts',
    hasMockData: true,
    notes: '@temp-api — not yet in fulfillment-service',
    pages: ['/provider/ai-setup', '/provider/catalog-studio'],
  },
  {
    route: 'v1/model_catalog_items',
    category: 'temp-api',
    ops: ['create', 'delete', 'get', 'list', 'patch'],
    missingOps: [],
    protoFile: null,
    hookFile: 'maas-catalog-item.ts',
    hasMockData: true,
    notes: '@temp-api — not yet in fulfillment-service',
    pages: ['/admin/catalog', '/catalog', '/models', '/models/create/:catalogItemId?', '/provider/catalog', '/provider/catalog-studio', '/provider/catalog-studio/new', '/provider/catalog/:id/edit', '/provider/catalog/new'],
  },
  {
    route: 'v1/model_accesses',
    category: 'temp-api',
    ops: ['create', 'get', 'list', 'patch'],
    missingOps: [],
    protoFile: null,
    hookFile: 'maas-instance.ts',
    hasMockData: true,
    notes: '@temp-api — not yet in fulfillment-service',
    pages: ['/models', '/models/create/:catalogItemId?'],
  },
  {
    route: 'v1/hubs',
    category: 'temp-api',
    ops: [],
    missingOps: [],
    protoFile: null,
    hookFile: null,
    hasMockData: true,
    notes: 'Private-only — no public proto',
    pages: [],
  },
  {
    route: 'v1/storage_backends',
    category: 'temp-api',
    ops: ['create', 'delete', 'get', 'list', 'patch'],
    missingOps: [],
    protoFile: null,
    hookFile: 'storage-backend.ts',
    hasMockData: true,
    notes: 'Private-only — no public proto',
    pages: ['/provider/storage-backends', '/provider/storage-backends/:id/edit', '/provider/storage-backends/new', '/provider/storage-tiers', '/provider/storage-tiers/:id/edit', '/provider/storage-tiers/new'],
  },
];
