/**
 * flow: dev
 * step: api_diff
 * route: /dev/api-diff
 *
 * Developer page: shows real vs. mock/temp API routes generated by scripts/gen-api-diff.mjs
 */
import { useMemo, useState } from 'react';
import {
  Label,
  TextInput,
  ToggleGroup,
  ToggleGroupItem,
  Toolbar,
  ToolbarContent,
  ToolbarItem,
  Tooltip,
} from '@patternfly/react-core';
import { Table, Tbody, Td, Th, Thead, Tr } from '@patternfly/react-table';

import { API_DIFF_MANIFEST, type ApiDiffEntry } from './api-diff-manifest.generated';
import ListPage from '../../components/Page/ListPage';
import ListPageBody from '../../components/Page/ListPageBody';

type CategoryFilter = 'all' | ApiDiffEntry['category'];

const CATEGORY_LABEL: Record<
  ApiDiffEntry['category'],
  { color: 'green' | 'orange' | 'grey'; text: string }
> = {
  real: { color: 'green', text: 'Real' },
  'temp-api': { color: 'orange', text: 'Temp API' },
  'proto-no-hook': { color: 'grey', text: 'Proto — no hook' },
};

const OPS_ORDER = ['list', 'get', 'create', 'patch', 'delete'];

function OpBadges({ ops, variant }: { ops: string[]; variant: 'green' | 'red' | 'blue' }) {
  const sorted = [...ops].sort((a, b) => OPS_ORDER.indexOf(a) - OPS_ORDER.indexOf(b));
  return (
    <>
      {sorted.map((op) => (
        <Label key={op} color={variant} isCompact style={{ marginRight: 3 }}>
          {op}
        </Label>
      ))}
    </>
  );
}

function CodeCell({ value }: { value: string | null }) {
  if (!value) {
    return <span style={{ color: 'var(--pf-t--global--color--nonstatus--gray--default)' }}>—</span>;
  }
  return <code style={{ fontSize: '0.8em' }}>{value}</code>;
}

export function ApiDiffPage() {
  const [categoryFilter, setCategoryFilter] = useState<CategoryFilter>('all');
  const [search, setSearch] = useState('');

  const counts = useMemo(
    () => ({
      real: API_DIFF_MANIFEST.filter((e) => e.category === 'real').length,
      'temp-api': API_DIFF_MANIFEST.filter((e) => e.category === 'temp-api').length,
      'proto-no-hook': API_DIFF_MANIFEST.filter((e) => e.category === 'proto-no-hook').length,
    }),
    [],
  );

  const filtered = useMemo(
    () =>
      API_DIFF_MANIFEST.filter((e) => {
        if (categoryFilter !== 'all' && e.category !== categoryFilter) {
          return false;
        }
        if (search && !e.route.toLowerCase().includes(search.toLowerCase())) {
          return false;
        }
        return true;
      }),
    [categoryFilter, search],
  );

  return (
    <ListPage
      title="API Diff"
      description="Auto-generated comparison of real proto-aligned vs. mock/temp API routes. Run pnpm gen:api-diff to refresh."
    >
      <ListPageBody>
        <div style={{ display: 'flex', gap: 8, marginBottom: 16, flexWrap: 'wrap' }}>
          <Label color="green">{counts.real} real</Label>
          <Label color="orange">{counts['temp-api']} temp-api</Label>
          <Label color="grey">{counts['proto-no-hook']} proto-no-hook</Label>
          <Label color="blue">{API_DIFF_MANIFEST.length} total</Label>
        </div>

        <Toolbar>
          <ToolbarContent>
            <ToolbarItem>
              <ToggleGroup aria-label="Filter by category">
                {(['all', 'real', 'temp-api', 'proto-no-hook'] as CategoryFilter[]).map((cat) => (
                  <ToggleGroupItem
                    key={cat}
                    text={cat === 'all' ? 'All' : CATEGORY_LABEL[cat].text}
                    isSelected={categoryFilter === cat}
                    onChange={() => setCategoryFilter(cat)}
                  />
                ))}
              </ToggleGroup>
            </ToolbarItem>
            <ToolbarItem>
              <TextInput
                placeholder="Filter by route…"
                value={search}
                onChange={(_e, v) => setSearch(v)}
                aria-label="Filter routes"
                style={{ minWidth: 240 }}
              />
            </ToolbarItem>
            <ToolbarItem variant="separator" />
            <ToolbarItem>{filtered.length} routes</ToolbarItem>
          </ToolbarContent>
        </Toolbar>

        <Table aria-label="API diff table" variant="compact">
          <Thead>
            <Tr>
              <Th>Route</Th>
              <Th>Category</Th>
              <Th>Ops implemented</Th>
              <Th>Missing ops</Th>
              <Th>Proto file</Th>
              <Th>Hook file</Th>
              <Th>Mock data</Th>
              <Th>Notes</Th>
            </Tr>
          </Thead>
          <Tbody>
            {filtered.map((entry) => {
              const cat = CATEGORY_LABEL[entry.category];
              return (
                <Tr key={entry.route}>
                  <Td>
                    <code style={{ fontSize: '0.85em' }}>{entry.route}</code>
                  </Td>
                  <Td>
                    <Label color={cat.color} isCompact>
                      {cat.text}
                    </Label>
                  </Td>
                  <Td>
                    {entry.ops.length > 0 ? (
                      <OpBadges ops={entry.ops} variant="blue" />
                    ) : (
                      <span>—</span>
                    )}
                  </Td>
                  <Td>
                    {entry.missingOps.length > 0 ? (
                      <OpBadges ops={entry.missingOps} variant="red" />
                    ) : null}
                  </Td>
                  <Td>
                    <CodeCell value={entry.protoFile} />
                  </Td>
                  <Td>
                    <CodeCell value={entry.hookFile} />
                  </Td>
                  <Td>
                    {entry.hasMockData ? (
                      <Label color="green" isCompact>
                        Yes
                      </Label>
                    ) : (
                      <Label color="grey" isCompact>
                        No
                      </Label>
                    )}
                  </Td>
                  <Td>
                    {entry.notes ? (
                      <Tooltip content={entry.notes}>
                        <span
                          style={{
                            maxWidth: 180,
                            overflow: 'hidden',
                            textOverflow: 'ellipsis',
                            whiteSpace: 'nowrap',
                            display: 'inline-block',
                            cursor: 'help',
                          }}
                        >
                          {entry.notes}
                        </span>
                      </Tooltip>
                    ) : null}
                  </Td>
                </Tr>
              );
            })}
          </Tbody>
        </Table>
      </ListPageBody>
    </ListPage>
  );
}
