//
// Copyright (c) 2025 Red Hat, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with
// the License. You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on
// an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the
// specific language governing permissions and limitations under the License.
//

// @generated by protoc-gen-es v2.12.0 with parameter "target=ts"
// @generated from file osac/public/v1/baremetal_instance_template_type.proto (package osac.public.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Metadata } from "./metadata_type_pb";
import { file_osac_public_v1_metadata_type } from "./metadata_type_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file osac/public/v1/baremetal_instance_template_type.proto.
 */
export const file_osac_public_v1_baremetal_instance_template_type: GenFile = /*@__PURE__*/
  fileDesc("CjVvc2FjL3B1YmxpYy92MS9iYXJlbWV0YWxfaW5zdGFuY2VfdGVtcGxhdGVfdHlwZS5wcm90bxIOb3NhYy5wdWJsaWMudjEixQEKGUJhcmVNZXRhbEluc3RhbmNlVGVtcGxhdGUSCgoCaWQYASABKAkSKgoIbWV0YWRhdGEYAiABKAsyGC5vc2FjLnB1YmxpYy52MS5NZXRhZGF0YRINCgV0aXRsZRgDIAEoCRITCgtkZXNjcmlwdGlvbhgEIAEoCRJMCg1zcGVjX2RlZmF1bHRzGAUgASgLMjUub3NhYy5wdWJsaWMudjEuQmFyZU1ldGFsSW5zdGFuY2VUZW1wbGF0ZVNwZWNEZWZhdWx0cyInCiVCYXJlTWV0YWxJbnN0YW5jZVRlbXBsYXRlU3BlY0RlZmF1bHRzYgZwcm90bzM", [file_osac_public_v1_metadata_type]);

/**
 * A bare metal instance template defines a hardware profile (host type, OS image, network configuration)
 * that can be used to create bare metal instances via a catalog item.
 *
 * @generated from message osac.public.v1.BareMetalInstanceTemplate
 */
export type BareMetalInstanceTemplate = Message<"osac.public.v1.BareMetalInstanceTemplate"> & {
  /**
   * Unique identifier of the template.
   *
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: osac.public.v1.Metadata metadata = 2;
   */
  metadata?: Metadata | undefined;

  /**
   * Human friendly short description of the template, suitable for displaying in one single line on a UI or CLI.
   *
   * @generated from field: string title = 3;
   */
  title: string;

  /**
   * Human friendly long description of the template, using Markdown format.
   *
   * @generated from field: string description = 4;
   */
  description: string;

  /**
   * Default spec values applied when creating a BareMetalInstance from this template.
   *
   * @generated from field: osac.public.v1.BareMetalInstanceTemplateSpecDefaults spec_defaults = 5;
   */
  specDefaults?: BareMetalInstanceTemplateSpecDefaults | undefined;
};

/**
 * Describes the message osac.public.v1.BareMetalInstanceTemplate.
 * Use `create(BareMetalInstanceTemplateSchema)` to create a new message.
 */
export const BareMetalInstanceTemplateSchema: GenMessage<BareMetalInstanceTemplate> = /*@__PURE__*/
  messageDesc(file_osac_public_v1_baremetal_instance_template_type, 0);

/**
 * Default values for bare metal instance spec fields.
 * No overridable spec fields are defined in this initial version; fields will be added in future
 * enhancements as tenant-configurable options are introduced (e.g. networking integration).
 *
 * @generated from message osac.public.v1.BareMetalInstanceTemplateSpecDefaults
 */
export type BareMetalInstanceTemplateSpecDefaults = Message<"osac.public.v1.BareMetalInstanceTemplateSpecDefaults"> & {
};

/**
 * Describes the message osac.public.v1.BareMetalInstanceTemplateSpecDefaults.
 * Use `create(BareMetalInstanceTemplateSpecDefaultsSchema)` to create a new message.
 */
export const BareMetalInstanceTemplateSpecDefaultsSchema: GenMessage<BareMetalInstanceTemplateSpecDefaults> = /*@__PURE__*/
  messageDesc(file_osac_public_v1_baremetal_instance_template_type, 1);

