//
// Copyright (c) 2026 Red Hat, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with
// the License. You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on
// an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the
// specific language governing permissions and limitations under the License.
//

// @generated by protoc-gen-es v2.12.0 with parameter "target=ts"
// @generated from file osac/public/v1/external_ip_pool_type.proto (package osac.public.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import { file_google_api_field_behavior } from "../../../google/api/field_behavior_pb";
import type { IPFamily } from "./ip_family_type_pb";
import { file_osac_public_v1_ip_family_type } from "./ip_family_type_pb";
import type { Metadata } from "./metadata_type_pb";
import { file_osac_public_v1_metadata_type } from "./metadata_type_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file osac/public/v1/external_ip_pool_type.proto.
 */
export const file_osac_public_v1_external_ip_pool_type: GenFile = /*@__PURE__*/
  fileDesc("Cipvc2FjL3B1YmxpYy92MS9leHRlcm5hbF9pcF9wb29sX3R5cGUucHJvdG8SDm9zYWMucHVibGljLnYxIrABCg5FeHRlcm5hbElQUG9vbBIKCgJpZBgBIAEoCRIqCghtZXRhZGF0YRgCIAEoCzIYLm9zYWMucHVibGljLnYxLk1ldGFkYXRhEjAKBHNwZWMYAyABKAsyIi5vc2FjLnB1YmxpYy52MS5FeHRlcm5hbElQUG9vbFNwZWMSNAoGc3RhdHVzGAQgASgLMiQub3NhYy5wdWJsaWMudjEuRXh0ZXJuYWxJUFBvb2xTdGF0dXMiTAoSRXh0ZXJuYWxJUFBvb2xTcGVjEjAKCWlwX2ZhbWlseRgDIAEoDjIYLm9zYWMucHVibGljLnYxLklQRmFtaWx5QgPgQQVKBAgCEAMiLgoURXh0ZXJuYWxJUFBvb2xTdGF0dXMSFgoJYXZhaWxhYmxlGAYgASgDQgPgQQNiBnByb3RvMw", [file_google_api_field_behavior, file_osac_public_v1_ip_family_type, file_osac_public_v1_metadata_type]);

/**
 * Represents a pool of external IP addresses available for allocation.
 *
 * ExternalIPPools are administrator-managed resources. The public API only surfaces pools that are
 * ready and have available capacity.
 * Tenants use this resource to discover available pools and select one when allocating an ExternalIP.
 *
 * @generated from message osac.public.v1.ExternalIPPool
 */
export type ExternalIPPool = Message<"osac.public.v1.ExternalIPPool"> & {
  /**
   * Unique identifier of the external IP pool.
   *
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * Metadata of the external IP pool, including name, labels, and timestamps.
   *
   * @generated from field: osac.public.v1.Metadata metadata = 2;
   */
  metadata?: Metadata | undefined;

  /**
   * Configuration of the external IP pool.
   *
   * @generated from field: osac.public.v1.ExternalIPPoolSpec spec = 3;
   */
  spec?: ExternalIPPoolSpec | undefined;

  /**
   * Current capacity information for this pool (system-provided, read-only).
   *
   * @generated from field: osac.public.v1.ExternalIPPoolStatus status = 4;
   */
  status?: ExternalIPPoolStatus | undefined;
};

/**
 * Describes the message osac.public.v1.ExternalIPPool.
 * Use `create(ExternalIPPoolSchema)` to create a new message.
 */
export const ExternalIPPoolSchema: GenMessage<ExternalIPPool> = /*@__PURE__*/
  messageDesc(file_osac_public_v1_external_ip_pool_type, 0);

/**
 * Defines the configuration of an ExternalIPPool.
 *
 * @generated from message osac.public.v1.ExternalIPPoolSpec
 */
export type ExternalIPPoolSpec = Message<"osac.public.v1.ExternalIPPoolSpec"> & {
  /**
   * IP address family for this pool. Immutable after creation.
   *
   * @generated from field: osac.public.v1.IPFamily ip_family = 3;
   */
  ipFamily: IPFamily;
};

/**
 * Describes the message osac.public.v1.ExternalIPPoolSpec.
 * Use `create(ExternalIPPoolSpecSchema)` to create a new message.
 */
export const ExternalIPPoolSpecSchema: GenMessage<ExternalIPPoolSpec> = /*@__PURE__*/
  messageDesc(file_osac_public_v1_external_ip_pool_type, 1);

/**
 * Capacity information for an ExternalIPPool exposed to tenants.
 *
 * @generated from message osac.public.v1.ExternalIPPoolStatus
 */
export type ExternalIPPoolStatus = Message<"osac.public.v1.ExternalIPPoolStatus"> & {
  /**
   * Number of IP addresses available for new allocations from this pool.
   *
   * @generated from field: int64 available = 6;
   */
  available: bigint;
};

/**
 * Describes the message osac.public.v1.ExternalIPPoolStatus.
 * Use `create(ExternalIPPoolStatusSchema)` to create a new message.
 */
export const ExternalIPPoolStatusSchema: GenMessage<ExternalIPPoolStatus> = /*@__PURE__*/
  messageDesc(file_osac_public_v1_external_ip_pool_type, 2);

