//
// Copyright (c) 2026 Red Hat, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with
// the License. You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on
// an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the
// specific language governing permissions and limitations under the License.
//

// @generated by protoc-gen-es v2.12.0 with parameter "target=ts"
// @generated from file osac/public/v1/tenant_type.proto (package osac.public.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Metadata } from "./metadata_type_pb";
import { file_osac_public_v1_metadata_type } from "./metadata_type_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file osac/public/v1/tenant_type.proto.
 */
export const file_osac_public_v1_tenant_type: GenFile = /*@__PURE__*/
  fileDesc("CiBvc2FjL3B1YmxpYy92MS90ZW5hbnRfdHlwZS5wcm90bxIOb3NhYy5wdWJsaWMudjEiagoGVGVuYW50EgoKAmlkGAEgASgJEioKCG1ldGFkYXRhGAIgASgLMhgub3NhYy5wdWJsaWMudjEuTWV0YWRhdGESKAoEc3BlYxgDIAEoCzIaLm9zYWMucHVibGljLnYxLlRlbmFudFNwZWMiHQoKVGVuYW50U3BlYxIPCgdkb21haW5zGAEgAygJYgZwcm90bzM", [file_osac_public_v1_metadata_type]);

/**
 * A tenant groups resources and users for a customer or business unit.
 *
 * @generated from message osac.public.v1.Tenant
 */
export type Tenant = Message<"osac.public.v1.Tenant"> & {
  /**
   * Unique identifier of the tenant.
   *
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: osac.public.v1.Metadata metadata = 2;
   */
  metadata?: Metadata | undefined;

  /**
   * @generated from field: osac.public.v1.TenantSpec spec = 3;
   */
  spec?: TenantSpec | undefined;
};

/**
 * Describes the message osac.public.v1.Tenant.
 * Use `create(TenantSchema)` to create a new message.
 */
export const TenantSchema: GenMessage<Tenant> = /*@__PURE__*/
  messageDesc(file_osac_public_v1_tenant_type, 0);

/**
 * @generated from message osac.public.v1.TenantSpec
 */
export type TenantSpec = Message<"osac.public.v1.TenantSpec"> & {
  /**
   * List of e-mail domains associated with this tenant.
   *
   * These are used to automatically redirect users to the correct identity provider during login. Each domain must be a
   * valid DNS hostname with only lowercase labels, for example `example.com` or `corp.example.org`. Uppercase letters
   * are rejected. Domains must be globally unique across all tenants.
   *
   * @generated from field: repeated string domains = 1;
   */
  domains: string[];
};

/**
 * Describes the message osac.public.v1.TenantSpec.
 * Use `create(TenantSpecSchema)` to create a new message.
 */
export const TenantSpecSchema: GenMessage<TenantSpec> = /*@__PURE__*/
  messageDesc(file_osac_public_v1_tenant_type, 1);

